kind: pipeline
name: default

steps:
  - name: publish docker image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.rtag.me/pilw
      registry: docker.rtag.me